#!/usr/bin/env node
// Runs after `vite build`, as the last step of `npm run build`.
//
// Strips the actual project data and the internal tools out of dist/ --
// everything under data/ and tools/ -- and embeds them as string constants
// that api/serve.ts serves instead, behind the access gate.
//
// This exists because a Vercel rewrite can never win against a static file
// sitting at the same request path (the filesystem is checked first), so
// the only way to make the gate function the one thing that can ever serve
// this content is to make sure nothing is left in dist/ for the filesystem
// to find. See api/serve.ts for the fuller version of this story.
//
// index.html and the JS/CSS bundle are deliberately left alone. They are
// generic app chrome with no project data baked in -- the app fetches
// data/projects.json and data/teams.json at runtime rather than embedding
// them in the bundle -- so an ungated visitor sees a branded, empty map and
// nothing else. Stripping index.html too was tried and reverted: Vercel's
// static build validation may require an index.html to exist at the output
// root, and that isn't a risk worth taking blind against a live deployment.

import { readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dist = join(root, 'dist');

const PROTECTED = [
  {
    path: '/data/projects.json',
    file: join(dist, 'data', 'projects.json'),
    type: 'application/json; charset=utf-8'
  },
  {
    path: '/data/teams.json',
    file: join(dist, 'data', 'teams.json'),
    type: 'application/json; charset=utf-8'
  },
  {
    path: '/tools/geocode.html',
    file: join(dist, 'tools', 'geocode.html'),
    type: 'text/html; charset=utf-8'
  },
  {
    path: '/tools/coords.html',
    file: join(dist, 'tools', 'coords.html'),
    type: 'text/html; charset=utf-8'
  }
];

const entries = {};
let missing = 0;
for (const { path, file, type } of PROTECTED) {
  if (!existsSync(file)) {
    console.warn(`[protect-build] expected ${file} for ${path} -- not found, skipping`);
    missing++;
    continue;
  }
  entries[path] = { body: readFileSync(file, 'utf-8'), contentType: type };
  rmSync(file);
}

writeFileSync(
  join(root, 'api', '_protected.generated.ts'),
  `// Generated by scripts/protect-build.mjs at build time. Not committed --\n` +
    `// see .gitignore. A Vercel build regenerates this before api/serve.ts\n` +
    `// is bundled, since buildCommand runs before the function build step.\n` +
    `export const PROTECTED: Record<string, { body: string; contentType: string }> =\n` +
    `  ${JSON.stringify(entries, null, 2)};\n`
);

for (const dir of [join(dist, 'data'), join(dist, 'tools')]) {
  if (existsSync(dir)) rmSync(dir, { recursive: true, force: true });
}

const kept = PROTECTED.length - missing;
console.log(`[protect-build] embedded ${kept}/${PROTECTED.length} file(s), stripped from dist/`);
if (missing > 0) {
  console.error(`[protect-build] ${missing} expected file(s) missing -- gate is incomplete`);
  process.exit(1);
}
